---
hosts: all
become: yes
tasks:
- name: install webserver on debian nodes
  apt:
   name: apache2 
  state: present
  when: ansible_os_family =="Debian"

-  name: install webserver on Redhat nodes
   yum:
     name: httpd
     state: present
     when: ansible_os_family =="Redhat"


